# SPDX-FileCopyrightText: Copyright (c) 2023-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: benchmark
'on':
  push:
    branches:
      - master
      - dev
    paths-ignore: [ 'README.md', '.github' ]
jobs:
  pr:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: ./rebuild_benchmark.sh
      - uses: peter-evans/create-pull-request@v7
        with:
          branch: benchmark
          commit-message: 'new benchmark results'
          delete-branch: true
          title: 'New results of benchmarking'
          assignees: yegor256
          base: master
