# SPDX-FileCopyrightText: Copyright (c) 2023-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: tarpaulin
'on':
  push:
    branches:
      - master
      - dev
jobs:
  tarpaulin:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: |-
          wget https://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb && \
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
      - uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.22.0' # the last version that supports tarpaulin@v0.1, which is no longer maintained.
          args: '--all-features --exclude-files src/lib.rs -- --test-threads 1'
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
